### ISSUE TITLE
Blog page template problems

### ISSUE THREAD

**Issue by NomadDevs** [GeoDirectory/GeoDirectory_framework#4]
The blog page template needs redone, i seem to get a good display if i create a page/blog/ and set the template as the blog template and in wp>settings>reading have " Your latest posts" (but i have GD set as homepage in GD settings).

But if in reading if i select "show static page" and select Posts page: blog, then the blog page shows full text and is not formatted as before, this setting should show like the setting above.

**Comment by mistergiri** [comment]
https://github.com/GeoDirectory/GeoDirectory_framework/pull/5
